### PR TITLE
Write Values to PI

### PR DESCRIPTION
**Pull request by ldariva**
I implemented a call to UpdateValue method which allows to send values to PI System. I tested this feature using a PI server in my company. I teste the code in Python 2.7.18, 3.5.4, 3.6.0 and 3.7.8. I also create two new enumartion. One for update option and another one for buffer option.

### CODE REVIEW

**Comment by ldariva** [comment]
What this checks do?

**Review by AlcibiadesCleinias — CHANGES_REQUESTED** [review]
so, I appreciate your contribution. 
I left some comments. Hope it may help.

Now I really time dependend and want to have some of the features you suggest as soon as possible, so that is why I started a new branch and it consists of 80% of your pr suggestions: https://github.com/Hugovdberg/PIconnect/pull/573

**Comment by Hugovdberg** [comment]
I think what happened is that @ldariva based his changes on the latest `master` branch or an older state of `develop`, and not on a recent commit to `develop`. I'm not sure how to remotely fix this. Perhaps if @ldariva could try to do the following we can get to a usefull pull request. As it stands right now I don't want to merge it, as several improvements from `develop` are reverted with these changes.

```shell
git pull origin develop # or perhaps git pull upstream develop. depending on how you've configured the git remotes
git rebase develop
```

**Comment by ldariva** [comment]
Hi Hugo,

I will ty that but I am not sure this is the problem. I took a log from the repository I worked with and this is the result.

commit b0258e7d5b3039c859295d1faf7f0170f3f3db04 (HEAD -> develop, origin/develop, origin/HEAD)
Author: ldariva <53340209+ldariva@users.noreply.github.com>
Date:   Wed Aug 5 22:01:19 2020 -0300

    Adjusted update_value.rst

commit 094f507384c29e4703a8e960c71a08b06ccc8fd8
Author: ALEX RIGON MULLER <ALEXMU02@braskem.com>
Date:   Wed Aug 5 21:44:42 2020 -0300

    Moved AFValue creation inside update_value method.

commit e52a57bf7e0c1b3d331eec2c4d64373f371efc19
Author: ldariva <53340209+ldariva@users.noreply.github.com>
Date:   Wed Aug 5 12:12:51 2020 -0300

    Added update_value feature to allow writting to PI

commit fed90e1108527cd21a2dff80a556495b583608ed
Merge: 985c93d d5fec92
Author: Hugo Lapr<C3><A9> <github@tbdwebdesign.nl>
Date:   Fri Mar 20 11:10:05 2020 +0100

    Merge pull request #524 from Hugovdberg/pyup/scheduled-update-2020-03-16

    Scheduled biweekly dependency update for week 11

commit d5fec92c6f1e592204c76bba687957c50856ce41
Author: Hugo Lapr<C3><A9> <hugo.lapre@brabantwater.nl>
Date:   Fri Mar 20 11:06:10 2020 +0100
:

**Pull request closed without merging**
